### ISSUE TITLE
testing README

### ISSUE THREAD

**Issue by eglassman** [alltom/debugview#1]
Was the provided example supposed to generate this error?

```
debugview eglassman$ node example01.js | debugview
/usr/local/bin/debugview: line 1: syntax error near unexpected token '('
/usr/local/bin/debugview: line 1: 'var BrowserDebugView = require('./browser-debug-view');'
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1036:11)
    at WriteWrap.afterWrite (net.js:794:14)
```

**Comment by eglassman** [comment]
The only line that mentions BrowserDebugView is line 1 of index.js:
`var BrowserDebugView = require('./browser-debug-view');`
which doesn't look like it has a syntax error!

**Comment by eglassman** [comment]
So, I'm learning about more about Node.js and I'm noticing that, even when I change index.js, the version of debug (`/usr/local/bin/debugview`) doesn't change. `npm restart` doesn't help. do you know how to refresh the cached copy of the app? I'm just not finding the right combo of terms to google.

**Comment by alltom** [comment]
1. It's supposed to work. But it had a bug. I just pushed version 0.0.3 and if you install again it should work this time.
2. `npm install` installs the latest release to a global directory, regardless of what you've checked out locally. That's probably not what you want, though. :) For local development, I recommend not installing it and running `node index.js` in the source directory instead of `debugview` to invoke it. I think you can use `npm link` to install it globally and have your edits reflected, but I've never tried that.

**Comment by eglassman** [comment]
It works now. Hooray!!
